server:
  port: 8082
  max-http-header-size: 64KB

spring:
  application:
    name: quickimageDEV

  cache:
    type: redis
    cache-names: rate-limit-buckets
  # --- ADD THIS SECTION ---
  data:
    redis:
      host: localhost
      port: 6379
  # ------------------------

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  storage:
    original-location: D:/quickimage/originals
    # Note: cache-location is technically unused now by our new logic!
    cache-location: D:/quickimage/cached
  image:
    original-width: 800
    original-height: 800
    max: 2050
    min: 10
    max-quality: 0.9
    min-quality: 0.2
    default-quality: 0.75

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: /api/v1/image/.* # Protects your image endpoints
      strategy: first
      http-response-body: "{ \"error\": \"Too many requests. Please slow down!\" }"
      rate-limits:
        - bandwidths:
            - capacity: 10
              time: 1
              unit: minutes
              refill-speed: interval # 10 new tokens every minute